import type { BuyEntity } from "@/entities/buy/type.ts";

export const getAllAvailableObjects = async (): Promise<BuyEntity[]> => {
  return [
    {
      id: "1",
      name: 'ЖК "Северная звезда"',
      price: "от 8,5 млн ₽",
      priceNum: 8.5,
      pricePerSqm: 130769,
      rooms: "4",
      area: 65,
      floor: 16,
      maxFloor: 16,
      status: "Готов к заселению",
      statusColor: "orange",
      district: "Северный",
      developer: "СтройИнвест",
      location: "Северный район",
      image:
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=160&h=160&fit=crop",
      amenities: ["Балкон", "Лифт", "Парковка"],
      nearTransport: true,
      nearSchool: false,
      nearShops: true,
      deliveryDate: "4 кв. 2024",
      sold: 45,
      total: 120,
      views: 1240,
      inquiries: 28,
      x: 45.03,
      y: 38.97,
    },
    {
      id: "2",
      name: 'ЖК "Новый Горизонт"',
      price: "от 5,2 млн ₽",
      priceNum: 5.2,
      pricePerSqm: 123810,
      rooms: "2",
      area: 42,
      floor: 25,
      maxFloor: 25,
      status: "Строительство",
      statusColor: "blue",
      district: "Центр",
      developer: "СтройИнвест",
      location: "Центр",
      image:
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=160&h=160&fit=crop",
      amenities: ["Французский балкон", "Лифт"],
      nearTransport: true,
      nearSchool: true,
      nearShops: true,
      deliveryDate: "2 кв. 2025",
      sold: 12,
      total: 84,
      views: 890,
      inquiries: 15,
      x: 45.02,
      y: 39.02,
    },
    {
      id: "3",
      name: 'ЖК "Парковый"',
      price: "от 6,8 млн ₽",
      priceNum: 6.8,
      pricePerSqm: 123636,
      rooms: "5",
      area: 55,
      floor: 12,
      maxFloor: 12,
      status: "Облицовка",
      statusColor: "green",
      district: "Южный",
      developer: "СтройИнвест",
      location: "Южный район",
      image:
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=160&h=160&fit=crop",
      amenities: ["Балкон", "Лифт", "Детская площадка"],
      nearTransport: false,
      nearSchool: true,
      nearShops: false,
      deliveryDate: "1 кв. 2025",
      sold: 31,
      total: 48,
      views: 2100,
      inquiries: 42,
      x: 45.01,
      y: 38.97,
    },
  ];
};
